ucat/main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
	path('c/<str:short>/',views.redirector, name = 'redirect'),
	path('',views.index , name = 'index'),
	path('add/',views.add,name='add'),
	path('register/',views.register,name = 'register'),
	path('signin/',views.signin,name = 'signin'),
	path('logout/',views.logout,name = 'logout'),
	path('delete/<str:short>',views.delete,name = 'delete'),
]

ucat/ucat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
]

ucat/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Link(models.Model):
	author  = models.ForeignKey(User, on_delete = models.CASCADE)
	link    = models.TextField()
	short   = models.CharField(max_length=250)
	publish = models.DateTimeField(default=timezone.now)
	crated_at  = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.link 

	class Meta:
		verbose_name = 'Ссылка'
		verbose_name_plural = 'Ссылки'

ucat/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User  


class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ('username','email','password1','password2')

	def save(self,commit=True):
		user = super(NewUserForm,self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

ucat/main/views.py
from .models import Link
from .forms import NewUserForm
from django.contrib.auth import login, authenticate
from django.contrib.auth import logout as auth_logout
from django.contrib import messages
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect,HttpResponse,HttpResponseNotFound
from django.views.decorators.http import require_http_methods
import random
import string

def get_random_string(length):
    letters = string.ascii_lowercase
    result_str = ''.join(random.choice(letters) for i in range(length))
    return result_str

def redirector(request, short): 
	link = get_object_or_404(Link, short = short)
	return render(request,'main/redirect.html',{'link':link})

def index(request):
	current_user = request.user 
	if current_user.id:
		username = current_user.username
		links = User.objects.get(id=current_user.id).link_set.order_by('-id')
		urls = []
		for link in links:
			urls.append(request.build_absolute_uri('c/'+link.short))
		ret = zip(links,urls)
		return render(request, 'main/index.html',{'links':links,'uid':current_user.id,'ret':ret,'username':username})
	else:
		return render(request, 'main/index.html',{'not_authorized':True})
def signin(request):
	if request.method == "POST":
		username = request.POST['username']
		pwd = request.POST['pwd']
		user = authenticate(username = username,password = pwd)
		if user is not None:
			login(request,user)
			return redirect('main:index')
		else:
			return render(request,'main/login.html',{'error':True})
	return render(request,'main/login.html')
def logout(request):
	auth_logout(request)
	return redirect('main:index')
def register(request):
	if request.method == "POST":
		print('123')
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request,user)
			messages.success(request,'Регистраия прошла успешно')
			return redirect('main:index')
		messages.error(request,'Неуспешная регистрация')
	form = NewUserForm()
	return render(request,'main/register.html',{'register_form':form})
def delete(request, short):
	if request.user.id:
		link = User.objects.get(pk = request.user.id).link_set.get(short=short) #находим ссылку и сразу проверяем делает ли запрос автор ссылки
		if link != None:
			link.delete()
			return redirect('main:index')
		else:
			return HttpResponse('Вы не являетесь автором данной ссылки и не можете его далить')
	return HttpResponse('Не авториирован!')
@require_http_methods(["POST"])
def add(request):
	if(request.user.id):
		link = request.POST['link']
		short = get_random_string(6)
		user = User.objects.get(pk=request.user.id)
		Link.objects.create(author=user,link=link,short=short)
		return HttpResponseRedirect('/')
	else:
		return HttpResponseNotFound('Not Allowed')

ucat/main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title> {% block title %} {% endblock %} </title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<style>
		a{
			color: #011120;
			font-weight: 500;
			text-decoration: none;
		}
		td{
			text-align: center;
		}
		i:hover{
			cursor: pointer;
			color:  red;
		}
		.table_header_item{
			text-align: center;
			color: white;
			padding: 20px 0;
			border-right;
			font-weight: 600;
		}
		.table_header{
			margin-top: 10px;
			border-top-left-radius: 8px;
			border-top-right-radius: 8px;
		}
		.link_item {
			padding: 15px 0;
		}
		.link_item div{
			text-align: center;
			color: black !important;
			font-weight: 600;
		}
		.link_item:nth-child(2n){
			background:#ededed;
		}
		.link_item:last-child{
			border-bottom-left-radius: 8px;
			border-bottom-right-radius: 8px;
		}
	</style>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css">
</head>
<body>
		<header>
			<nav class="navbar navbar-expand-lg navbar-light bg-light">
			  <a class="navbar-brand" href="/">Ucat</a>
			  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			    <span class="navbar-toggler-icon"></span>
			  </button>
			  <div class="collapse navbar-collapse" id="navbarNav">
			    <ul class="navbar-nav">
			    	<li class="nav-item">
				        <a class="nav-link" href="{% url 'main:index' %}">Главная</span></a>
				     </li>
			    	{% if request.user.id == Flase %}
			    	  <li class="nav-item">
				        <a class="nav-link" href="{% url 'main:signin' %}">Вход</span></a>
				      </li>
				      <li class="nav-item">
				        <a class="nav-link" href="{% url 'main:register' %}">Регистрация</a>
				      </li>
			    	{% else %}
				      <li class="nav-item">
				        <a class="nav-link" href="{% url 'main:logout' %}">Выход</a>
				      </li>
				    {% endif %}
			    </ul>
			  </div>
			</nav>
		</header>
		{% block content %}
		{% endblock %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script>
	var links = document.querySelectorAll('.link')
	console.log(links)
	links.forEach((link)=>{
		if(link.innerHTML.length > 30) link.innerHTML = link.innerHTML.slice(0,30)+"..."
	})
</script>
</body>
</html>

ucat/main/templates/main/index.html
{% extends "base.html" %}	
{% block title %}
	Main Page
{% endblock %}
{% block content %}

		{% if not_authorized %}
			<center style="margin: 20px 0;"><h4><a style="color:blue" href="{% url 'main:signin' %}">Войдите</a> что бы укорачивать ссылки</h4></center>
		{% else %}
			<center><h2>Мои ссылки</h2><h6>{{ username }}</h6></center>
			<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
			  <div class="modal-dialog" role="document">
			    <div class="modal-content">
			      <div class="modal-header">
			        <h5 class="modal-title" id="exampleModalLabel">Укоротить ссылку</h5>
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
			          <span aria-hidden="true">&times;</span>
			        </button>
			      </div>
			      <div class="modal-body">
			        <form action="{% url 'main:add' %}" method="POST">
			        	{% csrf_token %}
			          <div class="form-group">
			            <label for="recipient-name" class="col-form-label">Введите ссылку:</label>
			            <input type="text" class="form-control" id="recipient-name" name="link">
			          </div>
			          <div class="modal-footer">
				        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
				        <button type="submit" class="btn btn-primary">Добавить</button>
				      </div>
			        </form>
			      </div>

			    </div>
			  </div>
			</div>


	</div>
	<div class="custom_table container">
		<div class="table_header row bg-dark">
 			<div class="table_header_item col-md-3">Ссылка</div>
 			<div class="table_header_item col-md-3">Перенаправление</div>
 			<div class="table_header_item col-md-3">Дата создания</div>
 			<div class="table_header_item col-md-3">Действия</div>
		</div>
		<div class="links_list">
			{% for a,b in ret %}
					<div class="link_item row">
						<div class="col-md-3"><a href="{% url 'main:redirect' a.short %}">{{ b }}</a></div>
			 			<div class="col-md-3 link">{{ a.link }}</div>
			 			<div class="col-md-3">{{ a.publish }}</div>
			 			<div class="col-md-3"><a href="/delete/{{a.short}}"><i class="fa fa-trash" aria-hidden="true"></i></a></div>
					</div>
			{% endfor %}
		</div>
		<div class="row" style="margin-top:10px">
			<div class="col-md-2 offset-md-10">
				<button type="button" class="btn btn-dark" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">Добавить ссылку</button>
			</div>
		</div>
	</div>
	{% endif %}
{% endblock %}

ucat/main/templates/main/login.html
{% extends "base.html" %}
{% block title %}
	Войти
{% endblock title %}
{% block content %}
<center style="margin-top:20px;"><h2>Вход</h2></center>
		{% if error %}
				<div class="alert alert-danger alert-dismissible fade show" role="alert">
				  <strong>Ошибка</strong> Логин или пароль не верны.
				  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
				    <span aria-hidden="true">&times;</span>
				  </button>
				</div>
		{% endif %}
		<form method="POST">
			{% csrf_token %}
			<div class="form-group">
			    <label for="exampleInputEmail1">Логин</label>
			    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" name="username" autocomplete="1">
			</div>
			<div class="form-group">
			    <label for="exampleInputEmail1">Пароль</label>
			    <input type="password" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" name="pwd">
			 </div>

			<button type="submit" class="btn btn-primary">Войти</button>
		</form>
		<p class="text-center">Еще нет аккаунта? <a href="{% url 'main:register' %}"> Пройти регистрацию</a></p>

{% endblock content %}

ucat/main/templates/main/redirect.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	<center><a href="{{ link }}">Перейти на сайт</a></center>
	<center><a href="/">Главная</a></center>
</body>
</html>

ucat/main/templates/main/register.html
{% extends "base.html" %}
{% block title %}
	Пройти регистрацию
{% endblock title %}

{% load crispy_forms_filters %}

{% block content %}
	<center style="margin: 20px 0;"><h2>Регистария</h2></center>
	<form method="POST"> 
		{% csrf_token %}
		{{ register_form|crispy}}
		<button type="submit" class="btn btn-primary">Продолжить</button>
	</form>
	<p class="text-center">Уже есть аккаунт? <a href="{% url 'main:signin' %}"> Войти</a></p>
{% endblock content %}